AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'asedemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-secure-baseline'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'safaheem'
CICD_AGENT_TYPE: 'github'
CREATE_REDIS_RESOURCE: true
